version: '2.1'

services:
  mysql:
    restart: "always"
    image: mysql:5.6
    ports:
      - "3306:3306"
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_bin --default-storage-engine=INNODB --max_allowed_packet=256M --innodb_log_file_size=2GB --transaction-isolation=READ-COMMITTED --binlog_format=row"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
      MYSQL_USER: ${MYSQL_USER:-openmrs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
    healthcheck:
      test: "exit 0"
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

  backup:
    image: openmrs/cron-backup:1.0.0
    depends_on:
      - mysql
    volumes:
      - mysql-data:/mysql_data
      - ${BACKUP_DIR-./backups}:/backup
    environment:
      - DIRS=/mysql_data:mysql_data
      - SCHEDULE=0 0 * * *
    restart: always
    healthcheck:
      test: "exit 0"

volumes:
  mysql-data:
