version: '2.1'

services:
  oclclient:
    image: openmrs/ocl-client:qa
    environment:
      - OCL_API_HOST=${OCL_API_HOST:-https://api.qa2.aws.openconceptlab.org/}
      - TRADITIONAL_OCL_HOST=${TRADITIONAL_OCL_HOST:-https://qa2.openconceptlab.org}
      - ENVIRONMENT=${ENVIRONMENT:-qa}
    ports:
      - 8084:80
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-sSf", "localhost"]
