version: '2.1'

services:
  mysql:
    restart: "always"
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --max-allowed-packet=256M --default-storage-engine=INNODB --max_allowed_packet=256M --innodb_log_file_size=1GB"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
      MYSQL_USER: ${MYSQL_USER:-openmrs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
    healthcheck:
      test: "exit 0"
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  
  sonar:
    restart: always
    depends_on:
     mysql:
       condition: service_healthy
    image: sonarqube:6.7
    ports:
      - 9000:9000
    environment:
      SONARQUBE_JDBC_USERNAME: ${MYSQL_USER:-openmrs}
      SONARQUBE_JDBC_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
      SONARQUBE_JDBC_URL: ${SONAR_JDBC_URL:-jdbc:mysql://mysql:3306/openmrs?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance}
    healthcheck:
      test: ["CMD", "curl", "localhost:9000/api/system/health"]  
    volumes:
      - sonar-extensions:/opt/sonarqube/extensions

  backup:
    image: openmrs/cron-backup:1.0.0
    depends_on:
      mysql:
        condition: service_healthy
      sonar:
        condition: service_healthy
    volumes:
      - mysql-data:/mysql_data
      - sonar-extensions:/sonar_extensions
      - ${BACKUP_DIR-./backups}:/backup
    environment:
      - DIRS=/mysql_data:mysql_data,/sonar_extensions:sonar_extentions
      - SCHEDULE=0 0 * * *
    restart: always
    healthcheck:
      test: "exit 0"

volumes:
  mysql-data:
  sonar-extensions:
