version: '2.1'

services:
  oclclient:
    image: openmrs/ocl-client:qa
    environment:
      - OCL_API_HOST=${OCL_API_HOST:-https://api.qa.openconceptlab.org/}
      - TRADITIONAL_OCL_HOST=${TRADITIONAL_OCL_HOST:-https://qa.openconceptlab.org}
      - ENVIRONMENT=${ENVIRONMENT:-qa}
    ports:
      - 8081:80
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "-s", "http://localhost/"]
