version: '2.1'

services:
  db:
    restart: "always"
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin"
    environment:
      MYSQL_DATABASE: etherpad
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
      MYSQL_USER: ${MYSQL_USER:-etherpaduser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
    healthcheck:
      test: "exit 0"
    volumes:
       - ./dbdump:/docker-entrypoint-initdb.d
       - db-data:/var/lib/mysql

  etherpad:
    restart: "always"
    image: tvelocity/etherpad-lite:latest
    entrypoint: sh -c "chmod a+x /scripts/wait-for-it.sh && /scripts/wait-for-it.sh db:3306 -s --timeout=180 && /entrypoint.sh bin/run.sh --root"
    depends_on:
      - db
    ports:
      - "9001:9001"
    environment:
      ETHERPAD_ADMIN_USER: ${ADMIN_USER:-omrsadm}
      ETHERPAD_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-Admin123}
      ETHERPAD_DB_NAME: etherpad
      ETHERPAD_DB_HOST: db
      ETHERPAD_DB_USER: ${MYSQL_USER:-etherpaduser}
      ETHERPAD_DB_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
    volumes:
      - ./scripts:/scripts
      - etherpad-conf:/opt/etherpad-lite/var
      - etherpad-mods:/opt/etherpad-lite/node_modules/
      - /opt/etherpad-lite/node_modules/ep_etherpad-lite
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/"]
      timeout: 20s

  backup:
    image: openmrs/cron-backup:1.0.0
    depends_on:
      - etherpad
    volumes:
      - db-data:/mysql_data
      - etherpad-conf:/etherpad_conf
      - etherpad-mods:/etherpad_mods
      - ${BACKUP_DIR-./backups}:/backup
    environment:
      - DIRS=/mysql_data:mysql,/etherpad_conf:etherpad_conf,/etherpad_mods:etherpad_mods
      - SCHEDULE=0 0 * * *
    restart: always
    healthcheck:
      test: "exit 0"

volumes:
  db-data:
  etherpad-conf:
  etherpad-mods:
