version: "2.1"

services:
  oclclient:
    image: openmrs/ocl-client:stg
    environment:
      - OCL_API_HOST=${OCL_API_HOST:-https://api.staging.openconceptlab.org}
      - TRADITIONAL_OCL_HOST=${TRADITIONAL_OCL_HOST:-https://app.staging.openconceptlab.org}
      - OCL_SIGNUP_URL=${OCL_SIGNUP_URL:-https://app.staging.openconceptlab.org/#/accounts/signup}
      - OCL_GA_TOKENS=${OCL_GA_TOKENS}
      - ENVIRONMENT=${ENVIRONMENT:-stg}
    ports:
      - 8085:80
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-sSf", "localhost"]
